import uuid
import traceback
import logging
from typing import List, Optional
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session, joinedload

from dependencies import get_db, get_current_user, CurrentUser
from models import FactCandidate, ApprovalLog, ActionType, UserAccount, Department, RoleCode
from agents.step2_supervisor import get_memo_graph

logger = logging.getLogger(__name__)
router = APIRouter(tags=["Memos"])

# --- Schemas ---

class MemoCreateRequest(BaseModel):
    comment: str = Field(..., min_length=1, description="사용자가 입력한 원본 메모 내용")

class MemoResponse(BaseModel):
    id: uuid.UUID
    comment: str
    actor_id: uuid.UUID
    actor_name: str
    actor_department: Optional[str] = None
    logged_at: datetime
    action: str

class MemoThreadResponse(BaseModel):
    memos: List[MemoResponse]

# --- Router ---

@router.post("/facts/{fact_id}/memos", status_code=status.HTTP_201_CREATED)
def create_memo(
    fact_id: uuid.UUID,
    body: MemoCreateRequest,
    db: Session = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
):
    """지정된 Fact에 대한 메모를 생성하고 AI 에이전트를 통해 처리합니다."""
    fact = db.query(FactCandidate).filter(
        FactCandidate.id == fact_id,
        FactCandidate.company_id == current_user.company_id
    ).first()
    if not fact:
        raise HTTPException(status_code=404, detail="Fact not found")

    graph = get_memo_graph()
    initial_state = {
        "messages": [{"role": "user", "content": body.comment}],
        "context": {
            "row_id": str(fact_id),
            "user_id": str(current_user.id),
            "name": current_user.name,
            "email": current_user.email,
            "role_code": current_user.role_code.value,
            "company_id": str(current_user.company_id),
        },
    }

    try:
        final_state = graph.invoke(initial_state)
        payload = final_state.get("payload")

        if not payload:
            error_stage = final_state.get('error_stage', 'unknown')
            error_detail = final_state.get('error_detail', 'Payload was not generated by the agent.')
            logger.error(f"Agent failed to produce payload. Stage: {error_stage}, Detail: {error_detail}")
            raise HTTPException(
                status_code=500,
                detail={"message": "Agent execution failed.", "stage": error_stage, "detail": error_detail}
            )

        # Save to DB
        new_log = ApprovalLog(
            company_id=payload["company_id"],
            fact_candidate_id=payload["target_id"],
            actor_id=payload["actor_user_id"],
            action=ActionType(payload["memo_type"]),
            comment=payload["refined_message"],
            meta_data=payload,
        )
        db.add(new_log)
        db.commit()
        db.refresh(new_log)
        
        return {"detail": "Memo created successfully", "log_id": new_log.id}

    except Exception as e:
        db.rollback()
        logger.error(f"Error creating memo for fact {fact_id}: {e}", exc_info=True)
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(status_code=500, detail=f"Agent invocation error: {str(e)}")


@router.get("/facts/{fact_id}/memos", response_model=MemoThreadResponse)
def get_memo_thread(
    fact_id: uuid.UUID,
    db: Session = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
):
    """특정 Fact에 대한 메모 스레드를 조회합니다."""
    fact = db.query(FactCandidate).filter(FactCandidate.id == fact_id, FactCandidate.company_id == current_user.company_id).first()
    if not fact:
        raise HTTPException(status_code=404, detail="Fact not found")

    query = db.query(ApprovalLog).options(joinedload(ApprovalLog.actor).joinedload(UserAccount.department)).filter(ApprovalLog.fact_candidate_id == fact_id).order_by(ApprovalLog.logged_at.asc())

    if current_user.role_code != RoleCode.tenant_admin:
        admin_ids = [u.id for u in db.query(UserAccount.id).filter(UserAccount.company_id == current_user.company_id, UserAccount.role_code == RoleCode.tenant_admin).all()]
        allowed_actor_ids = [current_user.id] + admin_ids
        query = query.filter(ApprovalLog.actor_id.in_(allowed_actor_ids))

    logs = query.all()

    memos = [
        MemoResponse(
            id=log.id,
            comment=log.comment,
            actor_id=log.actor_id,
            actor_name=log.actor.name if log.actor else "Unknown",
            actor_department=log.actor.department.name if log.actor and log.actor.department else None,
            logged_at=log.logged_at,
            action=log.action.value,
        ) for log in logs if log.action in [ActionType.comment, ActionType.request_changes, ActionType.reject]
    ]
            
    return MemoThreadResponse(memos=memos)


@router.post("/memos/{memo_id}/acknowledge", status_code=status.HTTP_204_NO_CONTENT)
def acknowledge_memo(memo_id: uuid.UUID, db: Session = Depends(get_db), current_user: CurrentUser = Depends(get_current_user)):
    """메모를 '확인' 처리합니다."""
    memo = db.query(ApprovalLog).filter(ApprovalLog.id == memo_id, ApprovalLog.company_id == current_user.company_id).first()
    if not memo:
        raise HTTPException(status_code=404, detail="Memo not found")

    fact = memo.fact_candidate
    if not (current_user.role_code == RoleCode.tenant_admin or fact.assigned_user_id == current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to acknowledge this memo")

    memo.is_acknowledged = True
    db.commit()
    return